[0m19:17:33.515918 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1057a8750>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1057ce250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1057f1110>]}


============================== 19:17:33.518255 | 8546986d-5beb-4195-9f7a-dc9ad87d7daf ==============================
[0m19:17:33.518255 [info ] [MainThread]: Running with dbt=1.9.3
[0m19:17:33.518587 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/Users/juanherrera/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt init data-transform', 'send_anonymous_usage_stats': 'True'}
[0m19:17:53.268783 [debug] [MainThread]: Starter project path: /Users/juanherrera/Desktop/nyc-subway-analytics/.venv/lib/python3.11/site-packages/dbt/include/starter_project
[0m19:17:53.275237 [info ] [MainThread]: 
Your new dbt project "data_transform" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m19:17:53.275503 [info ] [MainThread]: Setting up your profile.
[0m19:17:57.079014 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 23.591595, "process_in_blocks": "0", "process_kernel_time": 0.123807, "process_mem_max_rss": "105152512", "process_out_blocks": "0", "process_user_time": 0.567306}
[0m19:17:57.079380 [debug] [MainThread]: Command `dbt init` succeeded at 19:17:57.079308 after 23.59 seconds
[0m19:17:57.079613 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1057f0a10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1008d6f90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1008d7090>]}
[0m19:17:57.079831 [debug] [MainThread]: Flushing usage events
[0m19:17:57.645355 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:35:25.647968 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10861b290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1085f4410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10863d010>]}


============================== 19:35:25.651760 | 26186957-990f-458d-ac57-8d69203997f3 ==============================
[0m19:35:25.651760 [info ] [MainThread]: Running with dbt=1.9.3
[0m19:35:25.652194 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/juanherrera/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:35:25.662912 [info ] [MainThread]: dbt version: 1.9.3
[0m19:35:25.663156 [info ] [MainThread]: python version: 3.11.5
[0m19:35:25.663314 [info ] [MainThread]: python path: /Users/juanherrera/Desktop/nyc-subway-analytics/.venv/bin/python
[0m19:35:25.663446 [info ] [MainThread]: os info: macOS-14.6.1-arm64-arm-64bit
[0m19:35:26.270458 [info ] [MainThread]: Using profiles dir at /Users/juanherrera/.dbt
[0m19:35:26.270795 [info ] [MainThread]: Using profiles.yml file at /Users/juanherrera/.dbt/profiles.yml
[0m19:35:26.270984 [info ] [MainThread]: Using dbt_project.yml file at /Users/juanherrera/Desktop/nyc-subway-analytics/dbt_project.yml
[0m19:35:26.271199 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m19:35:26.272358 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.65657043, "process_in_blocks": "0", "process_kernel_time": 0.128264, "process_mem_max_rss": "105234432", "process_out_blocks": "0", "process_user_time": 0.588317}
[0m19:35:26.272631 [debug] [MainThread]: Command `dbt debug` failed at 19:35:26.272571 after 0.66 seconds
[0m19:35:26.272859 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104d2eed0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104d2ee90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1083cf8d0>]}
[0m19:35:26.273076 [debug] [MainThread]: Flushing usage events
[0m19:35:26.729394 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:35:51.295787 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1053838d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1056a8150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1056f1110>]}


============================== 19:35:51.298316 | c1b4d18c-ae5e-44bf-9186-41d68655597f ==============================
[0m19:35:51.298316 [info ] [MainThread]: Running with dbt=1.9.3
[0m19:35:51.298706 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/Users/juanherrera/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt debug', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:35:51.305686 [info ] [MainThread]: dbt version: 1.9.3
[0m19:35:51.305916 [info ] [MainThread]: python version: 3.11.5
[0m19:35:51.306067 [info ] [MainThread]: python path: /Users/juanherrera/Desktop/nyc-subway-analytics/.venv/bin/python
[0m19:35:51.306200 [info ] [MainThread]: os info: macOS-14.6.1-arm64-arm-64bit
[0m19:35:51.369179 [info ] [MainThread]: Using profiles dir at /Users/juanherrera/.dbt
[0m19:35:51.369475 [info ] [MainThread]: Using profiles.yml file at /Users/juanherrera/.dbt/profiles.yml
[0m19:35:51.369627 [info ] [MainThread]: Using dbt_project.yml file at /Users/juanherrera/Desktop/nyc-subway-analytics/dbt_project.yml
[0m19:35:51.369821 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m19:35:51.370848 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.102850914, "process_in_blocks": "0", "process_kernel_time": 0.11341, "process_mem_max_rss": "104939520", "process_out_blocks": "0", "process_user_time": 0.553204}
[0m19:35:51.371083 [debug] [MainThread]: Command `dbt debug` failed at 19:35:51.371038 after 0.10 seconds
[0m19:35:51.371265 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1056f0150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1056f1450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1056bd690>]}
[0m19:35:51.371452 [debug] [MainThread]: Flushing usage events
[0m19:35:51.799767 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:36:21.072198 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107674790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1076cd590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1076f1390>]}


============================== 19:36:21.074177 | 8e8a9610-cc39-42d7-8d1a-2178c051b11b ==============================
[0m19:36:21.074177 [info ] [MainThread]: Running with dbt=1.9.3
[0m19:36:21.074493 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/juanherrera/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:36:21.078206 [info ] [MainThread]: dbt version: 1.9.3
[0m19:36:21.078395 [info ] [MainThread]: python version: 3.11.5
[0m19:36:21.078574 [info ] [MainThread]: python path: /Users/juanherrera/Desktop/nyc-subway-analytics/.venv/bin/python
[0m19:36:21.078710 [info ] [MainThread]: os info: macOS-14.6.1-arm64-arm-64bit
[0m19:36:21.122752 [info ] [MainThread]: Using profiles dir at /Users/juanherrera/.dbt
[0m19:36:21.123035 [info ] [MainThread]: Using profiles.yml file at /Users/juanherrera/.dbt/profiles.yml
[0m19:36:21.123185 [info ] [MainThread]: Using dbt_project.yml file at /Users/juanherrera/Desktop/nyc-subway-analytics/dbt_project.yml
[0m19:36:21.123365 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m19:36:21.124160 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.07852329, "process_in_blocks": "0", "process_kernel_time": 0.092477, "process_mem_max_rss": "106840064", "process_out_blocks": "0", "process_user_time": 0.544265}
[0m19:36:21.124360 [debug] [MainThread]: Command `dbt debug` failed at 19:36:21.124319 after 0.08 seconds
[0m19:36:21.124529 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107674350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10322eed0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10322e5d0>]}
[0m19:36:21.124700 [debug] [MainThread]: Flushing usage events
[0m19:36:21.484818 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:37:33.370646 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112f74650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112ff0f10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112ff15d0>]}


============================== 19:37:33.373450 | ce5196df-2d0f-4884-a8f7-79e52d2c9a22 ==============================
[0m19:37:33.373450 [info ] [MainThread]: Running with dbt=1.9.3
[0m19:37:33.373781 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/Users/juanherrera/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt debug', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m19:37:33.381039 [info ] [MainThread]: dbt version: 1.9.3
[0m19:37:33.381286 [info ] [MainThread]: python version: 3.11.5
[0m19:37:33.381473 [info ] [MainThread]: python path: /Users/juanherrera/Desktop/nyc-subway-analytics/.venv/bin/python
[0m19:37:33.381620 [info ] [MainThread]: os info: macOS-14.6.1-arm64-arm-64bit
[0m19:37:33.445733 [info ] [MainThread]: Using profiles dir at /Users/juanherrera/.dbt
[0m19:37:33.446010 [info ] [MainThread]: Using profiles.yml file at /Users/juanherrera/.dbt/profiles.yml
[0m19:37:33.446785 [info ] [MainThread]: Using dbt_project.yml file at /Users/juanherrera/Desktop/nyc-subway-analytics/dbt_project.yml
[0m19:37:33.447033 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m19:37:33.448111 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.107684165, "process_in_blocks": "0", "process_kernel_time": 0.11996, "process_mem_max_rss": "106758144", "process_out_blocks": "0", "process_user_time": 0.564586}
[0m19:37:33.448337 [debug] [MainThread]: Command `dbt debug` failed at 19:37:33.448282 after 0.11 seconds
[0m19:37:33.448537 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112ff11d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10509eed0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1139b5810>]}
[0m19:37:33.448719 [debug] [MainThread]: Flushing usage events
[0m19:37:34.092077 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:38:06.626256 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104df2810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104e693d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104e69a90>]}


============================== 19:38:06.628982 | 0902f0b2-5997-4cbd-8d99-471f303d8396 ==============================
[0m19:38:06.628982 [info ] [MainThread]: Running with dbt=1.9.3
[0m19:38:06.629322 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/Users/juanherrera/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt run --profile data_transform', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m19:38:06.629629 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/juanherrera/Desktop/nyc-subway-analytics/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:38:06.630560 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.0338345, "process_in_blocks": "0", "process_kernel_time": 0.104004, "process_mem_max_rss": "97878016", "process_out_blocks": "0", "process_user_time": 0.513952}
[0m19:38:06.630795 [debug] [MainThread]: Command `dbt run` failed at 19:38:06.630744 after 0.03 seconds
[0m19:38:06.630986 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104bffc90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104e69910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10155e910>]}
[0m19:38:06.631172 [debug] [MainThread]: Flushing usage events
[0m19:38:07.016045 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:01:30.261769 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1079734d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1079f2c10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1079f3790>]}


============================== 19:01:30.264778 | 6e681b93-22c3-4a00-bcab-1950481c0db7 ==============================
[0m19:01:30.264778 [info ] [MainThread]: Running with dbt=1.9.3
[0m19:01:30.266835 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/juanherrera/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt run --full-refresh', 'send_anonymous_usage_stats': 'True'}
[0m19:01:30.267169 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/juanherrera/Desktop/nyc-subway-analytics/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:01:30.268114 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.03800846, "process_in_blocks": "0", "process_kernel_time": 0.111669, "process_mem_max_rss": "97271808", "process_out_blocks": "0", "process_user_time": 0.505265}
[0m19:01:30.268361 [debug] [MainThread]: Command `dbt run` failed at 19:01:30.268301 after 0.04 seconds
[0m19:01:30.268567 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102d33b90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102d33410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1079f2e90>]}
[0m19:01:30.268730 [debug] [MainThread]: Flushing usage events
[0m19:01:30.722972 [debug] [MainThread]: An error was encountered while trying to flush usage events
